import { IParticle, IParticleSettings } from "./RevoltEffects";
import { Node } from "./util/LinkedList";
import { ParticleEmitter } from "./ParticleEmitter";
import { MovieClip } from "./MovieClip";
import { Sprite } from "./Sprite";
export declare class Particle extends Node implements IParticle {
    component: Sprite | MovieClip;
    duration: number;
    distance: number;
    startX: number;
    startY: number;
    deltaX: number;
    deltaY: number;
    distanceEase: Function;
    useAlpha: boolean;
    alphaStart: number;
    alphaDelta: number;
    alphaEase: Function;
    useTint: boolean;
    tintStart: number;
    tintEnd: number;
    tintEase: Function;
    useScale: boolean;
    scaleStart: number;
    scaleDelta: number;
    scaleEase: Function;
    useRotation: boolean;
    rotationSpeed: number;
    rotationEnd: number;
    useGravity: boolean;
    gravity: number;
    moveSpeedX: number;
    moveSpeedY: number;
    floorY: number;
    bounceFac: number;
    dx: number;
    dy: number;
    spawnOnComplete: ParticleEmitter;
    emitter: ParticleEmitter;
    settings: IParticleSettings;
    componentId: string;
    time: number;
    private _color;
    private _dt;
    constructor();
    init(emitter: ParticleEmitter, settings: IParticleSettings): void;
    update(dt: number): void;
    recycle(): void;
    dispose(): void;
}
